### ISSUE TITLE
mass update from remote

### ISSUE THREAD

**Issue by luceos** [hyn/git-helpers#2]

**Comment by luceos** [comment]
First implementation added to dev-master @franzliedke

**Comment by franzliedke** [comment]
Great. Just tested it, and it works really well for my Flarum's extensions directory. :)

The only directory where it failed was that of flarum-ext-flags, with the error message "fatal: No names found, cannot describe anything."

**Comment by luceos** [comment]
Can you give the output of `git remote -v` of that extension?

**Comment by franzliedke** [comment]
Quite normal:

> origin    git@github.com:flarum/flarum-ext-flags (fetch)
> origin  git@github.com:flarum/flarum-ext-flags (push)

**Comment by luceos** [comment]
And what does the output exactly say when using `-vvv` to increase verbosity? Any pinpointing to a specific line?

**Comment by luceos** [comment]
Had the same issue with an empty repository and with an extension that had no version yet.. That will be the issue.

**Comment by franzliedke** [comment]
Same output.

**Comment by luceos** [comment]
Fixed it ;)

**Comment by luceos** [comment]
Running a pull now on all those 37 packages as a test :smile:

**Comment by luceos** [comment]
Noticed an issue with branch identification. Fixing as we "speak".

**Comment by luceos** [comment]
tagged 0.1.2 and done

**Comment by franzliedke** [comment]
Before I try it out: What if I have uncommited or unpushed changes in one of these directories? Will it fail gracefully?

**Comment by luceos** [comment]
``` php
            // files not committed?!
            if (!$input->getOption('force') && $package->getCommitState()) {
                $output->writeln('<error>Local changes might be lost by pulling, commit/stash before continuing.</error>');
                continue;
            } else {
                $package->pullLatestChanges();
            }
```

There's a check for the commit state (modified, unknown files etc). I had no occurence in my workbench of this yet.

**Comment by luceos** [comment]
Running a test now.

**Comment by luceos** [comment]
```
hostingxs/search - version: 4.0.0
Local changes might be lost by pulling, commit/stash before continuing.
```

**Comment by luceos** [comment]
Please note the possible argument for the command to pull only matching directories.
