### ISSUE TITLE
commit + push command?

### ISSUE THREAD

**Issue by tobyzerner** [hyn/git-helpers#6]
Sometimes I make a similar change to a whole bunch of repositories, and want to do a new commit for each of them with the same message, then push. For example, I've just cleaned up a some linting config files in each of Flarum's extensions, and now I'm having to go through them one-by-one and commit my changes "Cleaned up some linting stuff" then push.

Do you think there is scope to add a commit/push helper to this utility?

I guess something like this doesn't happen very often so it might not be worth it – just a thought.

**Comment by luceos** [comment]
I'm using phpstorm relatively much to mass push the same commit message to several repositories, so I do understand the need for this. I'll put it on the todo, no promises on an eta though.
